### ISSUE TITLE
Running after installing from pip fails

### ISSUE THREAD

**Issue by kmccullen97** [kmccullen97/duro#2]
After running
```
pip3 install duro
```
and
```
duro
```
An error is thrown
```
Traceback (most recent call last):
  File "/home/kyle/.local/bin/duro", line 5, in <module>
    from duro.__main__ import run
  File "/home/kyle/.local/lib/python3.8/site-packages/duro/__main__.py", line 7, in <module>
    from duro.main import main
  File "/home/kyle/.local/lib/python3.8/site-packages/duro/main.py", line 4, in <module>
    from duro.database import Database
  File "/home/kyle/.local/lib/python3.8/site-packages/duro/database.py", line 4, in <module>
    from duro.models.board import BoardItem
ModuleNotFoundError: No module named 'duro.models'
```

**Note:** This error is not thrown when installing from test pypi
```
pip3 install -i https://test.pypi.org/simple/ duro
```

**Comment by kmccullen97** [comment]
It appears that folders `models`, `cmds` and `ui` are not included in the package.
```
~/.local/lib/python3.8/site-packages/duro$ ll
__init__.py
__main__.py
__pycache__/
board_ui.py
boards_menu.py
commands.py
config.py
database.py
footer.py
list_ui.py
main.py
```
